/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.system;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.DefaultListModel;

/**
 *
 * @author SI-MEXON
 */
public class PosGUI extends javax.swing.JFrame {

    /**
     * Creates new form PosGUI
     */
    public PosGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanelTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonTransaction = new javax.swing.JButton();
        jButtonCheck = new javax.swing.JButton();
        jButtonSearchForProduct = new javax.swing.JButton();
        jButtonContinueShopping = new javax.swing.JButton();
        jButtonCheckOut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAdminLogin = new javax.swing.JButton();
        jPanelMainBody = new javax.swing.JPanel();
        jPanelWelcome = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelSearchForProducts = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelContinueShopping = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelCheckOut = new javax.swing.JPanel();
        jLabelCheckOut = new javax.swing.JLabel();
        jCheckOutSeparator = new javax.swing.JSeparator();
        jPanelShoppingCart = new javax.swing.JPanel();
        jLabelShoppingCart = new javax.swing.JLabel();
        jButtonPurchase = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jList1 = new javax.swing.JList<>();
        jSeparator3 = new javax.swing.JSeparator();
        jPanelAddProductsToCart = new javax.swing.JPanel();
        jPanelCategorySelect = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListCategories = new javax.swing.JList<>();
        jPanelProductSelect = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListProduct = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanelAdmin = new javax.swing.JPanel();
        jTextFieldCreateCategory = new javax.swing.JTextField();
        jButtonCreateCategory = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemSavePurchase = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(821, 514));
        setPreferredSize(new java.awt.Dimension(902, 571));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTab.setBackground(new java.awt.Color(204, 204, 204));
        jPanelTab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel1.setText("Views");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel2.setText("In-Store Purchases");

        jButtonTransaction.setBackground(java.awt.Color.darkGray);
        jButtonTransaction.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        jButtonTransaction.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jButtonTransaction.setText("Transaction");

        jButtonCheck.setBackground(java.awt.Color.darkGray);
        jButtonCheck.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        jButtonCheck.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jButtonCheck.setText("Check");

        jButtonSearchForProduct.setBackground(java.awt.Color.darkGray);
        jButtonSearchForProduct.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        jButtonSearchForProduct.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jButtonSearchForProduct.setText("Search For Prod");
        jButtonSearchForProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSearchForProductMouseClicked(evt);
            }
        });
        jButtonSearchForProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchForProductActionPerformed(evt);
            }
        });

        jButtonContinueShopping.setBackground(java.awt.Color.darkGray);
        jButtonContinueShopping.setFont(new java.awt.Font("Sitka Subheading", 0, 12)); // NOI18N
        jButtonContinueShopping.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jButtonContinueShopping.setText("Continue Shopping");
        jButtonContinueShopping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonContinueShoppingMouseClicked(evt);
            }
        });

        jButtonCheckOut.setBackground(java.awt.Color.darkGray);
        jButtonCheckOut.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        jButtonCheckOut.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jButtonCheckOut.setText("Check Out");
        jButtonCheckOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCheckOutMouseClicked(evt);
            }
        });
        jButtonCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckOutActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel3.setText("Online Purchases");

        javax.swing.GroupLayout jPanelTabLayout = new javax.swing.GroupLayout(jPanelTab);
        jPanelTab.setLayout(jPanelTabLayout);
        jPanelTabLayout.setHorizontalGroup(
            jPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabLayout.createSequentialGroup()
                .addGroup(jPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(jPanelTabLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelTabLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonContinueShopping, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButtonSearchForProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTabLayout.setVerticalGroup(
            jPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonTransaction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCheck)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSearchForProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonContinueShopping)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCheckOut)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(230, 230, 230))
        );

        getContentPane().add(jPanelTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 510));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Admin");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 49, -1));

        jButtonAdminLogin.setBackground(new java.awt.Color(102, 102, 102));
        jButtonAdminLogin.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButtonAdminLogin.setText("LogIn");
        jButtonAdminLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAdminLoginMouseClicked(evt);
            }
        });
        jButtonAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdminLoginActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 70, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 140, 40));

        jPanelMainBody.setBackground(new java.awt.Color(153, 153, 153));
        jPanelMainBody.setLayout(new java.awt.CardLayout());

        jPanelWelcome.setLayout(new java.awt.GridLayout(1, 0));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mexonShoppingSystem resource/Mexon Shopping SytemsWelcome.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanelWelcome.add(jLabel9);

        jPanelMainBody.add(jPanelWelcome, "card5");

        jPanelSearchForProducts.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Search For Products");

        javax.swing.GroupLayout jPanelSearchForProductsLayout = new javax.swing.GroupLayout(jPanelSearchForProducts);
        jPanelSearchForProducts.setLayout(jPanelSearchForProductsLayout);
        jPanelSearchForProductsLayout.setHorizontalGroup(
            jPanelSearchForProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchForProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(745, Short.MAX_VALUE))
        );
        jPanelSearchForProductsLayout.setVerticalGroup(
            jPanelSearchForProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchForProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(523, Short.MAX_VALUE))
        );

        jPanelMainBody.add(jPanelSearchForProducts, "cardSearchForProducts");

        jPanelContinueShopping.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Continue Shopping");

        javax.swing.GroupLayout jPanelContinueShoppingLayout = new javax.swing.GroupLayout(jPanelContinueShopping);
        jPanelContinueShopping.setLayout(jPanelContinueShoppingLayout);
        jPanelContinueShoppingLayout.setHorizontalGroup(
            jPanelContinueShoppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContinueShoppingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(753, Short.MAX_VALUE))
        );
        jPanelContinueShoppingLayout.setVerticalGroup(
            jPanelContinueShoppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContinueShoppingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(523, Short.MAX_VALUE))
        );

        jPanelMainBody.add(jPanelContinueShopping, "cardContinueShopping");

        jPanelCheckOut.setBackground(java.awt.Color.lightGray);
        jPanelCheckOut.setOpaque(false);
        jPanelCheckOut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCheckOut.setFont(new java.awt.Font("TakaoPGothic", 1, 16)); // NOI18N
        jLabelCheckOut.setText("Check Out");
        jPanelCheckOut.add(jLabelCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanelCheckOut.add(jCheckOutSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 460, 10));

        jPanelShoppingCart.setBackground(new java.awt.Color(255, 255, 255));
        jPanelShoppingCart.setOpaque(false);

        jLabelShoppingCart.setFont(new java.awt.Font("Purisa", 0, 14)); // NOI18N
        jLabelShoppingCart.setText("Shopping Cart");

        jButtonPurchase.setBackground(java.awt.Color.gray);
        jButtonPurchase.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jButtonPurchase.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPurchase.setText("Purchase");
        jButtonPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPurchaseMouseClicked(evt);
            }
        });

        jScrollPane1.setBorder(null);

        jPanel4.setLayout(new java.awt.GridLayout(0, 1));

        jList1.setBackground(new java.awt.Color(250, 255, 248));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jPanel4.add(jList1);

        jScrollPane1.setViewportView(jPanel4);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanelShoppingCartLayout = new javax.swing.GroupLayout(jPanelShoppingCart);
        jPanelShoppingCart.setLayout(jPanelShoppingCartLayout);
        jPanelShoppingCartLayout.setHorizontalGroup(
            jPanelShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShoppingCartLayout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelShoppingCart)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShoppingCartLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanelShoppingCartLayout.setVerticalGroup(
            jPanelShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShoppingCartLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabelShoppingCart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanelCheckOut.add(jPanelShoppingCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 240, 470));

        jPanelAddProductsToCart.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAddProductsToCart.setOpaque(false);
        jPanelAddProductsToCart.setLayout(new java.awt.CardLayout());

        jPanelCategorySelect.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCategorySelect.setOpaque(false);
        jPanelCategorySelect.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel7.setText("Select Category");
        jPanelCategorySelect.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jPanelCategorySelect.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 10));

        jListCategories.setBackground(getBackground());
        jListCategories.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListCategories.setFixedCellHeight(25);
        jListCategories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListCategoriesValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(jListCategories);

        jPanelCategorySelect.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 430, 330));

        jPanelAddProductsToCart.add(jPanelCategorySelect, "CategorySelect");

        jPanelProductSelect.setOpaque(false);
        jPanelProductSelect.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel8.setText("Select Product");
        jPanelProductSelect.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanelProductSelect.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 10));

        jListProduct.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListProduct.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListProductValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListProduct);

        jPanelProductSelect.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 430, 310));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add To Cart");
        jPanelProductSelect.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 130, -1));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Select Category");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelProductSelect.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 20));

        jPanelAddProductsToCart.add(jPanelProductSelect, "ProductSelect");

        jPanelCheckOut.add(jPanelAddProductsToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 520, 510));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mexonShoppingSystem resource/Mexon Shopping SytemsMain.png"))); // NOI18N
        jLabel10.setVerifyInputWhenFocusTarget(false);
        jPanelCheckOut.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 550));

        jPanelMainBody.add(jPanelCheckOut, "cardCheckOut");

        jButtonCreateCategory.setText("Create Category");
        jButtonCreateCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdminLayout = new javax.swing.GroupLayout(jPanelAdmin);
        jPanelAdmin.setLayout(jPanelAdminLayout);
        jPanelAdminLayout.setHorizontalGroup(
            jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCreateCategory)
                    .addComponent(jTextFieldCreateCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(462, Short.MAX_VALUE))
        );
        jPanelAdminLayout.setVerticalGroup(
            jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jTextFieldCreateCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCreateCategory)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        jPanelMainBody.add(jPanelAdmin, "cardAdmin");

        getContentPane().add(jPanelMainBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 900, 550));

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jMenuFile.setText("File");

        jMenuItemSavePurchase.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItemSavePurchase.setText("Save Purchase");
        jMenuFile.add(jMenuItemSavePurchase);

        jMenuItemExit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemExitMouseClicked(evt);
            }
        });
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdminLoginActionPerformed
        CardLayout c1 = (CardLayout) jPanelMainBody.getLayout();
        c1.show(jPanelMainBody, "cardAdmin");
    }//GEN-LAST:event_jButtonAdminLoginActionPerformed

    private void jButtonSearchForProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSearchForProductMouseClicked
        jButtonSearchForProduct.setBackground(Color.white);
        jButtonTransaction.setBackground(Color.DARK_GRAY);
        jButtonCheck.setBackground(Color.DARK_GRAY);
        jButtonContinueShopping.setBackground(Color.DARK_GRAY);
        jButtonCheckOut.setBackground(Color.DARK_GRAY);

        jButtonSearchForProduct.setForeground(Color.black);
        jButtonTransaction.setForeground(Color.white);
        jButtonCheck.setForeground(Color.white);
        jButtonContinueShopping.setForeground(Color.white);
        jButtonCheckOut.setForeground(Color.white);

        CardLayout c1 = (CardLayout) jPanelMainBody.getLayout();
        c1.show(jPanelMainBody, "cardSearchForProducts");
        //This function displays the search for products panel when it is clicked

    }//GEN-LAST:event_jButtonSearchForProductMouseClicked

    private void jButtonSearchForProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchForProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSearchForProductActionPerformed

    private void jButtonCheckOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCheckOutMouseClicked
        jButtonSearchForProduct.setBackground(Color.DARK_GRAY);
        jButtonTransaction.setBackground(Color.DARK_GRAY);
        jButtonCheck.setBackground(Color.DARK_GRAY);
        jButtonContinueShopping.setBackground(Color.DARK_GRAY);
        jButtonCheckOut.setBackground(Color.white);

        jButtonSearchForProduct.setForeground(Color.white);
        jButtonTransaction.setForeground(Color.white);
        jButtonCheck.setForeground(Color.white);
        jButtonContinueShopping.setForeground(Color.white);
        jButtonCheckOut.setForeground(Color.black);

        CardLayout c1 = (CardLayout) jPanelMainBody.getLayout();
        c1.show(jPanelMainBody, "cardCheckOut");
        CardLayout c2 = (CardLayout) jPanelAddProductsToCart.getLayout();
        c2.show(jPanelAddProductsToCart, "CategorySelect");

        //This function displays the "CheckOut" panel when it is clicked and 
        //also set a specific colour on the jbutton 
        DefaultListModel<String> catModel = new DefaultListModel();
        for (String category : Purchases.ListCategories()) {
            catModel.addElement(category);
        }
        jListCategories.setModel(catModel);
//        Purchases.ListCategories();

    }//GEN-LAST:event_jButtonCheckOutMouseClicked

    private void jButtonContinueShoppingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinueShoppingMouseClicked
        jButtonSearchForProduct.setBackground(Color.DARK_GRAY);
        jButtonTransaction.setBackground(Color.DARK_GRAY);
        jButtonCheck.setBackground(Color.DARK_GRAY);
        jButtonContinueShopping.setBackground(Color.white);
        jButtonCheckOut.setBackground(Color.DARK_GRAY);

        jButtonSearchForProduct.setForeground(Color.white);
        jButtonTransaction.setForeground(Color.white);
        jButtonCheck.setForeground(Color.white);
        jButtonContinueShopping.setForeground(Color.black);
        jButtonCheckOut.setForeground(Color.white);

        CardLayout c1 = (CardLayout) jPanelMainBody.getLayout();
        c1.show(jPanelMainBody, "cardContinueShopping");
    }//GEN-LAST:event_jButtonContinueShoppingMouseClicked

    private void jButtonPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPurchaseMouseClicked
        System.out.println("Purchase");
        //how to create a loop that will display n number of jButtons and if any of the jButtons is clicked run the same function
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPurchaseMouseClicked

    private void jMenuItemExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemExitMouseClicked
//        javax.swing.JOptionPane.showMessageDialog(this, "Hello GUI World");
//        javax.swing.JOptionPane.showMessageDialog(rootPane, evt, "Exit?", HEIGHT);
        System.exit(0);
//Got a Problem here to work on later

    }//GEN-LAST:event_jMenuItemExitMouseClicked

    private void jButtonAdminLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdminLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdminLoginMouseClicked

    private void jListCategoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListCategoriesValueChanged
        // read up list selection changed event model and the use of the getValueIsAdjusting() function
        if (!evt.getValueIsAdjusting()) {
            String cat = jListCategories.getSelectedValue();

            CardLayout c1 = (CardLayout) jPanelAddProductsToCart.getLayout();
            c1.show(jPanelAddProductsToCart, "ProductSelect");
            
            System.out.println(cat + " is selected from categories");
            
            DefaultListModel<String> catModel = new DefaultListModel();
            for (String products : Purchases.ListItems(cat)) {
                catModel.addElement(products);
            }
            jListCategories.setModel(catModel);
        }
    }//GEN-LAST:event_jListCategoriesValueChanged

    private void jButtonCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCheckOutActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jListProductValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListProductValueChanged
        // TODO add your handling code here:
        //Displays the products available in the selected category
    }//GEN-LAST:event_jListProductValueChanged

    private void jButtonCreateCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateCategoryActionPerformed
        String categoryToCreate = jTextFieldCreateCategory.getText();
        Product.createCategory(categoryToCreate);
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreateCategoryActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PosGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PosGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PosGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PosGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAdminLogin;
    private javax.swing.JButton jButtonCheck;
    private javax.swing.JButton jButtonCheckOut;
    private javax.swing.JButton jButtonContinueShopping;
    private javax.swing.JButton jButtonCreateCategory;
    private javax.swing.JButton jButtonPurchase;
    private javax.swing.JButton jButtonSearchForProduct;
    private javax.swing.JButton jButtonTransaction;
    private javax.swing.JSeparator jCheckOutSeparator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCheckOut;
    private javax.swing.JLabel jLabelShoppingCart;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListCategories;
    private javax.swing.JList<String> jListProduct;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemSavePurchase;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAddProductsToCart;
    private javax.swing.JPanel jPanelAdmin;
    private javax.swing.JPanel jPanelCategorySelect;
    private javax.swing.JPanel jPanelCheckOut;
    private javax.swing.JPanel jPanelContinueShopping;
    private javax.swing.JPanel jPanelMainBody;
    private javax.swing.JPanel jPanelProductSelect;
    private javax.swing.JPanel jPanelSearchForProducts;
    private javax.swing.JPanel jPanelShoppingCart;
    private javax.swing.JPanel jPanelTab;
    private javax.swing.JPanel jPanelWelcome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldCreateCategory;
    // End of variables declaration//GEN-END:variables
}
